# Generated by Django 4.1 on 2022-08-24 10:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name=django.contrib.auth.models.User),
        ),
    ]
